### ISSUE TITLE
Error appears after installing CinemaMachine from package manager inside Dkvfx project.

### ISSUE THREAD

**Issue by PockPocket** [keijiro/Dkvfx#14]
Hi,

I get these 3 similar errors after installing CinemaMachine from package manager:

 

C:\Program Files\Unity\2019.3.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.ugui\Runtime\UI\Core\InputField.cs(1628,40): error CS0246: The type or namespace name 'Event' could not be found (are you missing a using directive or an assembly reference?)

C:\Program Files\Unity\2019.3.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.ugui\Runtime\UI\Core\InputField.cs(1804,34): error CS0246: The type or namespace name 'Event' could not be found (are you missing a using directive or an assembly reference?)

C:\Program Files\Unity\2019.3.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.ugui\Runtime\UI\Core\InputField.cs(1798,17): error CS0246: The type or namespace name 'Event' could not be found (are you missing a using directive or an assembly reference?)

 

Anyone as an idea of what could cause that and is there any fix possible ?

Thanks in advance !

Mathieu.

**Comment by keijiro** [comment]
Try enabling the built-in UIElements package from the Package Manager UI.

(This is an issue on the Cinemachine side where it doesn't provide dependencies to the built-in packages).

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by PockPocket** [comment]
Hi, thanks for answering back. I've tried to enable the built-in UIElements package from the Package Manager UI and got more errors. 
<img width="1917" alt="Errors" src="https://user-images.githubusercontent.com/73412598/113536549-5fd67f00-95a4-11eb-95d7-4ecd033b6547.PNG">

**Comment by PockPocket** [comment]
I then decided to quit and re-open the project and those were the errors that were there : 
<img width="1918" alt="Errors_after_Rebbot" src="https://user-images.githubusercontent.com/73412598/113536642-87c5e280-95a4-11eb-84fc-99ecc7e9c482.PNG">

**Comment by keijiro** [comment]
Is HDRP 7.1 compatible with Cinemachine 2.7? I'm not sure as I have never used Chinemachine. Forum would be helpful.

**Comment by PockPocket** [comment]
I checked for compatibility between these two and HDRP 7.1 only works with CinemaMachine 2.3.3. Thanks for your help it is much appreciated I will now be able to get my renders done all in one place :).
